### ISSUE TITLE
How do I use the "network" object from useVis()

### ISSUE THREAD

**Issue by fredkorts** [Xedii/vis-network-hook#1]
Hey! I wanted to create some drag events so that I could get the current co-ordinates of my nodes, but I can't figure it out. Can you show me an example of how I should write custom events?

**Comment by Xedii** [comment]
Hi! What do you mean by "custom event" ?

I created for you an example with a few events from the vis-network website 😉

https://codesandbox.io/s/festive-swanson-yv74c?fontsize=14&hidenavigation=1&theme=dark&file=/src/Graph.js

**Comment by lauriskuznecovs** [comment]
@Xedii I thing your answer with examples makes sens and this issue can be closed.
